# Generated by Django 3.2.7 on 2021-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_url',
            field=models.URLField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon_url',
            field=models.URLField(default=None, max_length=2000, null=True),
        ),
    ]
